version: "3.10"
services:
 app:
  build: .
  volumes:
   - .:/django
  ports:
  - "8000:8000"
  image: app:django
  container_name: my_first_django_container
  command: python website.py runserver 0.0.0.0:8000